name: sus_nfc_tag_editor
description: "SUS NFC Tag Editor: lector y editor versátil de etiquetas NTAG216 de dudosa procedencia."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  nfc_manager: ^4.2.1
  package_info_plus: ^10.2.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
